### ISSUE TITLE
关于CPL OJ平台题目

### ISSUE THREAD

**Issue by ICermanRan** [RoyH0427/NJUSZ-Intelligent-Software-and-Engineering#1]
同学你好，我是一名非NJU的学生，对于NJU CPL课程的OJ题目和课程项目非常感兴趣，通过您的仓库完成了一定的练习。但是后续题目可能因为同学学业繁忙，没有空更新。我这边想继续往后面做，想问一下，是否方便添加个联系方式，可以有偿。

**Comment by Planetes1mal** [comment]
最近期末周没有时间整理并发布23届的题目，期末结束了我会陆续上传后续

**Comment by ICermanRan** [comment]
> 最近期末周没有时间整理并发布23届的题目，期末结束了我会陆续上传后续

感谢

**Comment by Planetes1mal** [comment]
> 同学你好，我是一名非NJU的学生，对于NJU CPL课程的OJ题目和课程项目非常感兴趣，通过您的仓库完成了一定的练习。但是后续题目可能因为同学学业繁忙，没有空更新。我这边想继续往后面做，想问一下，是否方便添加个联系方式，可以有偿。

2023秋季学期CPL的题目（所有我能接触到的）已经全部上传了
